---

- hosts: servers # all
  become: true
  tasks:

  - name: install docker package
    apt: 
      name: docker
      state: latest

  - name: update repository index
    apt:
      update_cache: yes

  - name: remove outdated packages
    apt:
      autoremove: true
