---

- hosts:  all 
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    dnf: 
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: webservers
  become: true
  tasks:

  - name: install docker and apache2 packages
    apt: 
      name: 
        - docker
        - apache2
      state: latest
      autoremove: true
    when: ansible_distribution in ["Ubuntu", "Debian"]


  - name: install docker httpd and php packages
    dnf: 
      name:
    #    - docker
        - httpd
        - php
      state: latest
      autoremove: true
    when: ansible_distribution == "CentOS"


- hosts: dbservers
  become: true
  tasks:
  
  - name: install mariadb package (CentOS)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

 
  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: fileservers
  become: true
  tasks:
  
  - name: install samba package
    package:
      name: samba
      state: latest
