---

- hosts: servers # all
  become: true
  tasks:

  - name: install docker and apache2 packages
    apt: 
      name: 
        - docker
        - apache2
      state: latest
      update_cache: yes
      autoremove: true
    when: ansible_distribution in ["Ubuntu", "Debian"]


  - name: install docker httpd and php packages
    dnf: 
      name:
        - docker
        - httpd
        - php
      state: latest
      autoremove: true
      update_cache: yes
    when: ansible_distribution == "CentOS"
