---

- hosts: servers # all
  become: true
  tasks:

  - name: install docker package
    apt: 
      name: docker
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: remove outdated packages
    apt:
      autoremove: true
    when: ansible_distribution in ["Debian", "Ubuntu"]




  - name: install docker package
    dnf: 
      name: docker
      state: latest
    when: ansible_distribution == "CentOS"

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install php package
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS" 

  - name: remove outdated packages
    dnf:
      autoremove: true
    when: ansible_distribution == "CentOS"



