---

- hosts: webservers  
  become: true
  tasks:

  - name: uninstall docker and apache packages (Ubuntu)
    apt: 
      name: 
        - docker
        - apache2
        - mariadb-server
      state: absent
      purge: yes
      autoremove: yes
      autoclean: yes
    when: ansible_distribution == "Ubuntu"


  - name: uninstall docker and php packages (CentOS)
    dnf: 
      name: 
        - docker
        - php
        - mariadb
      state: absent
      purge: yes
      autoremove: yes
      autoclean: yes
    when: ansible_distribution == "CentOS"


- hosts: fileservers
  become: true
  tasks:
 
  - name: remove samba package
    package:
      name: samba
      state: absent
      purge: yes
      autoremove: yes
      autoclean: yes
