---
- hosts: base
  become: true
  roles:
    - base


- hosts: webservers
  become: true
  roles:
    - webservers


- hosts: dbservers
  become: true
  roles:
    - dbservers


- hosts: fileservers
  become: true
  roles:
    - fileservers
