- name: install mariadb server package (CentOS)
  tags: db, maria
  dnf: 
    name: mariadb
    state: absent
  when: ansible_distribution == "CentOS"

- name: install mariadb server package (Ubuntu)
  tags: db, maria
  apt: 
    name: mariadb-server
    state: absent
  when: ansible_distribution == "Ubuntu"
