- name: install apache,php and bind9 package 
  tags: httpd
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
      - "{{ bind9_package_name }}"
    state: latest

- name: start and enable apache service
  tags: http, apache
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
