- name: install httpd package (CentOS)
  tags: httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: start and enable httpd (CentOS)
  tags: http, apache
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"


- name: install hpache2 package (Ubuntu)
  tags: apache2
  apt:
    name:
      - apache2
      - bind9
    state: latest
  when: ansible_distribution == "Ubuntu"
